### ISSUE TITLE
Add Blocked Number Of Players Online

### ISSUE THREAD

**Issue by TheIntelloBox** [Minecrell/ServerListPlus#124]
Hello,

Could you add a system where the number of player is blocked ?
For example, All day long, there is a fake number of players : 6.

Thanks. :D

**Comment by Minecrell** [comment]
Personally, I do not support faking the online players. Is there a special reason why you want to do this?

**Comment by Minecrell** [comment]
Please re-open this issue or comment here again if you still need this. Closing this for now.

**Comment by TheIntelloBox** [comment]
Because, this is for trolling. xD

**Comment by rubota** [comment]
You guys are sending this to the wrong email. Not sure how mine got into the mix

**Comment by Minecrell** [comment]
@rubota You are receiving notifications because you are watching the repository: https://github.com/Minecrell/ServerListPlus/watchers

@TheIntelloBox SLP supports changing the online player count. I'm not going to document it but of course you can figure out how to use it yourself (it's quite simple) :P
