### ISSUE TITLE
Unable to change player count text in ServerListPlusServer

### ISSUE THREAD

**Issue by ColtonDRG** [Minecrell/ServerListPlus#138]
I'm making use of ServerListPlusServer for my minigames server (basically, people log into the main server to start up the minigame, then there's some scripts on the host machine that start up the minigames server with the correct settings. Whenever there is no ongoing minigame, the server shuts down and scripts on the backend start up a ServerListPlusServer to let people know there is no ongoing minigame and to connect to the main server). I'm trying to change the player count text as described here: https://github.com/Minecrell/ServerListPlus/wiki/Player-Slots but I seem to be unable to do so. No matter what I change there, it just says "ServerListPlus" in the &4 colour.

**Comment by Minecrell** [comment]
The player slots text will only show if SLP is sure that the connecting player is really using the same Minecraft version as the server (because otherwise the player slots will replace the Minecraft version that is displayed).

By default, SLPServer doesn't know which Minecraft version it is supposed to represent, that must be configured separately. However, if you **always** want to show the note that people should connect to the main server, you could just change the outdated version name instead of setting custom player slots which will yield the same result.

See https://github.com/Minecrell/ServerListPlus/wiki/Status-Configuration#outdated-version for instructions how to change the outdated version name.

**Comment by ColtonDRG** [comment]
Oh, I understand. I didn't get that before. I use ProtocolSupport on all my servers, so they support all versions going WAAAY back, so I didn't think about it that way. Thanks. :)
