### ISSUE TITLE
Client out of date

### ISSUE THREAD

**Issue by Someone-NEW** [Minecrell/ServerListPlus#152]
I have a problem with the latest version that Hover is not to see Player counts work but i see Client out of date! and Hover is not to see Server is 1.10.2 my launcher is 1.10.2 but still not see my Hover can you please fix that?

And i have no error but i found something info here that is so strange but i CANT use Hover whatever i do.
https://github.com/Minecrell/ServerListPlus/wiki/Player-Slots

**Comment by Minecrell** [comment]
Do you have ProtocolLib installed? Also please copy your configuration to https://gist.github.com/ or similar and paste the link here.

**Comment by Someone-NEW** [comment]
Hello yes i have ProtocolLib but i have right all installed LibsDisguise an ProtocolLib from another reason for my 1.10.2 reason other not work right that i have is ok. http://pastebin.com/diWYKxQS

**Comment by Minecrell** [comment]
Sorry, I meant the SLP configuration, not the ProtocolLib configuration.

**Comment by Someone-NEW** [comment]
Ok here is one of them http://pastebin.com/q7eupYHy this one is just for test by me.

**Comment by Minecrell** [comment]
@Someone-NEW OK, the reason why it is not working is because you made a small mistake in your configuration.

First, your server is displayed as "out-of-date" because you are using the [Custom Player Slots](https://github.com/Minecrell/ServerListPlus/wiki/Player-Slots#problems) feature. This happens due to the way this feature works, so you'll either need to accept it or remove the custom slots from your configuration. It will however not prevent people from joining your server (they can join even though your server is displayed as outdated).

Second, if you start your server you should get a warning like this:

```
[WARNING] [ServerListPlus] [Core] Unknown configuration property: Hover @ FaviconConf
[WARNING] [ServerListPlus] [Core] Unknown configuration property: Hover @ FaviconConf
```

What this means is that you have added the `Hover` option in the configuration in the wrong place. You have added it as part of the `Favicon` option, but it must be under `Players` instead.

So you need to take this part: https://gist.github.com/Minecrell/88c2855a6ad0778ff4c3c8607f84a0a7#file-yml-L55-L73
And move it up under player so that it looks like this: https://gist.github.com/Minecrell/73d0214f9d9fa5c4381a72148893d54b

The same applies to your other `Hover` part of your configuration.

**Comment by Someone-NEW** [comment]
by reload on console is all ok http://imgur.com/a/4xAcZ i will check this what you mean about wrong place while on old i have no any problem with hover..

**Comment by Minecrell** [comment]
As I said, if you want to use [Custom Player Slots](https://github.com/Minecrell/ServerListPlus/wiki/Player-Slots), you will need to accept that it displays the out of date message, there is no way around that. If you don't want that, turn off the feature.

**Comment by Someone-NEW** [comment]
Hmm ok thank you i hope this will be fixed in the feature, from Mojang? this is not from plugin side bug?

**Comment by Minecrell** [comment]
It's unlikely that this will be ever fixed, it's not an actual feature of the Minecraft client. When the client/server is outdated it will display the Minecraft version sent by a server. The custom player slots work by always making the server outdated and setting the custom player slots as the Minecraft version the server is running.

**Comment by Mysx-rage** [comment]
Okay i know this post is long dead but im running into the same issues but the custom player join thing is not enabled im not quite sure whats causing this issue
