### ISSUE TITLE
/cmd to view the result in game w/o logging out

### ISSUE THREAD

**Issue by sibomots** [Minecrell/ServerListPlus#169]
Perhaps I missed a step.  Is it reasonable for a command to view the effect of a change to the MoTD in-game w/o having to log out?

Thanks.

**Comment by Minecrell** [comment]
The chat interface isn't really best to check how a MOTD (that is, the one from the server list) looks like, because it looks different to the server list background. Additionally, you need to edit the config manually anyway, so you could just use the server console to reload and keep the client in the server list.

**Comment by Minecrell** [comment]
@sibomots I'm going to close this for now. Let me know if you want to discuss this further. :)
