### ISSUE TITLE
Virtual-Host shows default MOTD

### ISSUE THREAD

**Issue by GamingGeek** [Minecrell/ServerListPlus#170]
I have multiple IPs for my server and I want to have a different MOTD for each IP, so I added them in the hosts section. But it only shows the normal MOTD...
![2017-08-28_16 36 53](https://user-images.githubusercontent.com/29981918/29780842-2c207c26-8c0f-11e7-87c4-09b3551d6a19.png)
This is how I have it listed in my MC:
- SpectralMC (P) is play.spectralmc.tk
- SpectralMC {M) is mc.spectralmc.tk (Both of these are fine)
- Spectral Beta Access is spectralbeta.sk (I want this to tell players to do /beta to access beta features, not a different server)
- Spectral Dev Server is spectraldev.tk (I want this to loop through current projects in the MOTD)

But they all show the default MOTD.... Any fix?

**Comment by Minecrell** [comment]
Can you copy your configuration to http://gist.github.com/ and post the link here so I can check if something's wrong?

**Comment by GamingGeek** [comment]
https://gist.github.com/GamingGeek/3b956b59e63e0c13aa591eb37fd8fcdehttps://gist.github.com/GamingGeek/3b956b59e63e0c13aa591eb37fd8fcde

**Comment by Minecrell** [comment]
My first guess would be that the main `Personalized` section overrides the `Default` section for the virtual hosts. There are a few ways to fix that:

- Since you don't actually use the `%player%` feature currently, you can just remove the `Personalized` section entirely from your configuration. There is no need to have the same in `Default` and `Personalized`; the plugin will always fall back to `Default` if it doesn't exist.

    You can remove `Personalized` entirely, like here: https://gist.github.com/Minecrell/56150fc0e765af80195c5e50d71d2124#file-serverlistplus-yml-L35-L70

- The other workaround would be to add `Personalized` to each virtual host so the main one does no longer override the ones from the virtual host.

**Comment by GamingGeek** [comment]
Didn't work... I did think of something else that might be affecting it is that I use Cloudflare to manage my domains DNS, so I'll play around with that and reply if anything changes.

**Comment by GamingGeek** [comment]
I setup an A record in my domain provider's DNS area and it now works!
![igotthe](https://user-images.githubusercontent.com/29981918/29790343-6c3e18be-8c31-11e7-9f41-148ad9573d87.PNG)

**Comment by Minecrell** [comment]
Awesome!
