### ISSUE TITLE
Wrong UUID

### ISSUE THREAD

**Issue by WatermelonPL** [Minecrell/ServerListPlus#251]
SLP tries to get skin from UUID 44ea26384bc635f89bb64f8983fa555a, instead of (actual) 99e73a99f33c41b3ab8d63f3fba0e28c

**Comment by Minecrell** [comment]
I need more information to help you. Is your server running in offline mode?

**Comment by WatermelonPL** [comment]
Yes

**Comment by Minecrell** [comment]
Unfortunately, I cannot provide support for offline mode servers.

Using offline mode changes the UUID for all players, because the UUIDs are no longer fetched from Mojang. Those "fake" UUIDs won't have a skin. But SLP does not know what kind of UUID it is dealing with, because it simply tracks the player UUIDs provided by the server.

I would recommend that you change your server to online mode. This will fix the problem.
