### ISSUE TITLE
Head Favicons dont work anymore.

### ISSUE THREAD

**Issue by ImaEternal** [Minecrell/ServerListPlus#257]
I tried using
Favicon:
     Heads:
     - %_UUID_%

Returned:
[Server] WARN [Core] Unable to load favicon from SKIN_HEAD: f0a666fe-2a09-466d-bd0f-0cc880166d9f -> java.io.IOException: Server returned HTTP response code: 429 for URL: https://sessionserver.mojang.com/session/minecraft/profile/f0a666fe2a09466dbd0f0cc880166d9f

Tried:
 Favicon:
    URLs:
    # Visage uses X-Steve to indicate the default skin
    - https://visage.surgeplay.com/bust/64/X-Steve

Returned:
https://visage.surgeplay.com/bust/64/f0a666fe2a09466dbd0f0cc880166d9f -> javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

Also tried other avatar websites
- URL: https://mc-heads.net/combo/f0a666fe2a09466dbd0f0cc880166d9f.png -> javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
- Unable to load favicon from URL: https://cravatar.eu/head/f0a666fe2a09466dbd0f0cc880166d9f/64.png -> javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

Please fix, thank you.

**Comment by Minecrell** [comment]
`
[Server] WARN [Core] Unable to load favicon from SKIN_HEAD: f0a666fe-2a09-466d-bd0f-0cc880166d9f -> java.io.IOException: Server returned HTTP response code: 429 for URL: https://sessionserver.mojang.com/session/minecraft/profile/f0a666fe2a09466dbd0f0cc880166d9f
`

means too many requests have been sent, just try again after an hour or so.

As for `javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure`

In general, that means that something is wrong with your or the other server's Internet connection or your Java version. I don't think this can be fixed in SLP. Those other websites are out of my control.

**Comment by ImaEternal** [comment]
Been trying for a day, Internet is fine. Can you look further into this issue? when the link is pressed the icon displays fine.

**Comment by Minecrell** [comment]
Which Java version are you running?

**Comment by ImaEternal** [comment]
Java 10.0.01 (64BIT) 
Java 8 Update 171
Java 8 Update 191

**Comment by ImaEternal** [comment]
It wouldn’t matter anyway, it’s hosted on a hosting website. They use latest

**Comment by Minecrell** [comment]
Well, then something is likely broken on the hosting website... Maybe they use an outdated Java version or have configured something that prevents SLP from working properly.

It's definitely not an issue in SLP I'm afraid. It will probably work if you try it locally. (I just tried it, it works fine...)
