### ISSUE TITLE
RGB Support

### ISSUE THREAD

**Issue by untuned** [Minecrell/ServerListPlus#295]
1.16 has added RGB support for chat colors using hex. I would like to be able to use this to further customize my MOTD.

**Comment by Minecrell** [comment]
That sounds nice but in practice I don't see an easy way to support that. Using RGB colors likely requires using JSON text components, but SLP was not designed to support these (back when it was written there was little to no support for JSON text components). The same applies to Bukkit, which lacks support for JSON in many APIs (including the `ServerListPingEvent` used by SLP).

The easiest way would be if someone comes up with a standard way to specify those similar to color codes (e.g. `&#fffff`) and then patches that into all the APIs that still accept strings instead of JSON text components...

**Comment by Andre601** [comment]
You may not need any JSON support for this at all.
You can for example just use `ChatColor.of("#rrggbb")` in any normal String and send this normally using the `sendMessage()` method and the displayed text will have the provided color.
Only thing to do there is to use the ChatColor class of net.md_5 and not org.bukkit, which comes with some small downsides.
Alternatively *should* providing `§xrrggbb` already be sufficient enough since that's basically what the ChatColor API does with its `of` functions.

I can't tell if it is as easy on a MOTD as the normal chat, but it would be worth a try and you could always ask for sure.

**Comment by Minecrell** [comment]
PRs are welcome as usual :)

**Comment by solo-development** [comment]
I'll take a look into this for a PR but no promises.

**Comment by GiansCode** [comment]
Debating on tackling this. Though, I'd use a [thirdparty](https://www.spigotmc.org/threads/hexitextlib-hex-colours-custom-fonts-development-library.456057/) lib to handle HEX, as well as retain pre 1.16 support. 

Doesn't break any of his licensing. Though, not sure how we stand on external libs here.

**Comment by SirOMGitsYOU** [comment]
Someone has forked it to include RGB support. https://github.com/Minebench/ServerListPlus

**Comment by GiansCode** [comment]
There's also an [open](https://github.com/Minecrell/ServerListPlus/pull/308) PR here

**Comment by RedstoneFuture** [comment]
https://github.com/Phoenix616/MineDown

**Comment by Andre601** [comment]
> Maybe this library can help too: https://github.com/Phoenix616/MineDown

The format isn't really intuitive. Many people either want to use `&#<hex>` or `<#<hex>>`, but MineDown has imo a horrible approach on that.
Also, there's already a fork implementing this format: https://github.com/Minebench/ServerListPlus

**Comment by Phoenix616** [comment]
> The format isn't really intuitive. Many people either want to use `&#<hex>` or `<#<hex>>`, but MineDown has imo a horrible approach on that.

Minedown supports `&#<hex>`

**Comment by tst-038** [comment]
Title: Hex translator
Description: Works like ChatColor.translateAlternateColorCodes()


//Example:
string coloredmessage = translateHex("#ffffffThis Is #ddef4eColored Text");


public static String translateHex(String message){
    String newtext = "";
    String[] format = message.split("(?<=#)(?=#)|(?<= )(?=#)|(?<=#)(?= )#?([\\da-fA-F]{2})([\\da-fA-F]{2})([\\da-fA-F]{2})");
    for (String t: format) {
        newtext +=  net.md_5.bungee.api.ChatColor.of(t.substring(0,7)) + t.substring(7);
    }
    return newtext;
}

**Comment by Minecrell** [comment]
For anyone who was desperately waiting for this, it turns out RGB colors can already be used on Bukkit/Bungee even on the good old ServerListPlus 3.4.8 from 2017:

```yaml
  Description:
  - |-
    &x&4&5&b&f&5&5A Minecraft Server.
    &x&0&2&8&8&d&1Now with RGB colors.
```

For Bungee this just works, for Bukkit this only worked without ProtocolLib. ProtocolLib has a fix in [build 501](https://ci.dmulloy2.net/job/ProtocolLib/) now (see https://github.com/dmulloy2/ProtocolLib/pull/1152).

Of course, this syntax is terrible, so I added some code to SLP to also accept a nicer syntax:

```yaml
  Description:
  - |-
    &#45bf55A Minecraft Server.
    &#0288d1Now with RGB colors.
```

I've also added a simple gradient placeholder to simplify creating those:

```yaml
  Description:
  - |-
    &#45bf55A Minecraft &#0288d1Server.
    %gradient#ffbe00#f4511e%Now with RGB colors. Nice!%gradient%
```

![](https://user-images.githubusercontent.com/3035868/117149387-77797100-adb7-11eb-9751-58d75e66bf98.png)

It can also be used with more than two colors or placeholders in it:

```yaml
  Description:
  - |-
    %gradient#ffbe00#f4511e%Now with RGB colors. Hello %player%!%gradient%
    %gradient#45bf55#00abd8#45bf55%|||||||||||||||||||||||||||||||| %online%/%max% ||||||||||||||||||||||||||||||||%gradient%
```

![](https://user-images.githubusercontent.com/3035868/117150876-d8ee0f80-adb8-11eb-8509-c952af60644a.png)

I hope that covers most use cases :)
