### ISSUE TITLE
Support for Authentication in Standalone Server

### ISSUE THREAD

**Issue by AwesomestCode** [Minecrell/ServerListPlus#299]
Would it be possible to authenticate users before they get displayed with the message for the standalone server? I plan on forking ServerListPlus for a lightweight verification system, in which each user logs on to the server to get a verification code. ServerListPlus standalone seems to be a great base for that lightweight server, however, for obvious reasons that would require cracked user checking.

Also, do you have a Discord server or something I can use to communicate through?

**Comment by AwesomestCode** [comment]
After reading several more issues, I realize that you a) do not check Discord frequently and b) have lost interest in Minecraft. I've looked at [wiki.vg's authentication protocol page](https://wiki.vg/Protocol_Encryption#Authentication) and I would like to try to implement it in SLP. However, I'm not really familiar with how SLP works, so could you please point me in the right direction to do this?

**Comment by Minecrell** [comment]
There are probably lots of existing server implementations around, which already have authentication implemented. For SLP this obviously doesn't make a lot of sense (since it doesn't need authentication). It might be easier to take something else as a base.

Otherwise you would basically need to modify code in https://github.com/Minecrell/ServerListPlus/tree/master/Server/src/main/java/net/minecrell/serverlistplus/server/network, add some additional packet handlers for the authentication stuff, talk to Mojang servers etc.

**Comment by AwesomestCode** [comment]
The reason I was using SLP is because of its lightweight ness. Anything that actually bothers to handle worlds is way too heavy for my usage, making SLP the perfect candidate for this. However, if this is impossible then I may use BungeeCord instead. Thank you.

**Comment by Minecrell** [comment]
Not impossible, it depends if you want to write the code for authentication yourself :P

**Comment by AwesomestCode** [comment]
I’ll probably first write the code in a BungeeCord plugin for time’s sake; I grossly underestimated the time this release would take to write. After I get the version with BungeeCord working I’ll try implementing it in the more lightweight SLP.
