### ISSUE TITLE
UUID and player info not updating

### ISSUE THREAD

**Issue by Eejit43** [Minecrell/ServerListPlus#341]
Hello!
I have been trying to implement custom favicons per player, and I have noticed that players on the same IP address don't actually get marked as separate players in PlayerCache.json, and so favicons and player-specific information doesn't change (at least until that player logs in and overwrites the file). Is there any fix for this, or is it a bug?

**Comment by Minecrell** [comment]
The player IP is the only tracking information SLP has. If two (or more) players on the same address have the same IP address, SLP can not distinguish between them. Unfortunately, one of them will always see the wrong player in that case.

There is no way to fix this because Minecraft does not provide any way (except the IP) to identify a player in a status ping.
