### ISSUE TITLE
Alternative Color for RGB Text for Clients Below 1.16

### ISSUE THREAD

**Issue by Epharal1** [Minecrell/ServerListPlus#344]
RGB color doesn't display for clients below 1.16. It would be nice to have the ability to select an alternative old-school color code (&0 to &f) that will display in place of RGB text or gradients for older clients.

If no alternative color code was provided, we could calculate the closest color. Other plugins already do this.

Currently if older clients ping the server, they see "random" colors. (It probably renders the first 4 bits of the RGB color code.)

Possible syntax would be: #00AAAA3 - 3 represents the &3 code (which in this case is exactly the same as the hex code before, but this is just an example).

**Comment by Minecrell** [comment]
Hmm yeah I see how that could be useful, but not sure this is very simple to implement with the current code :/

**Comment by Minecrell** [comment]
I think something that might work is to provide an option to _remove **all** RGB colors_ for clients < 1.16.

You could then put another color immediately before the RGB color code, that would be preserved and therefore show on older clients. On newer clients, the old color will be replaced with the RGB color immediately after. e.g. something like

```
  Description:
  - |-
    &a&#45bf55A Minecraft &9&#0288d1Server.
    &e%gradient#ffbe00#f4511e%Now with RGB colors. Nice!%gradient%
```

Calculating closed color could also work but not sure I want to complexity of that given that it will look totally terrible for gradients anyway. I'd rather remove the RGB colors then and provide options to set a different color instead.

Does that sound good too?

**Comment by Epharal1** [comment]
Yeah, that would be good I guess.

Or, another option that I thought of is to maybe have a completely different description for older clients? I don't think that should be hard to implement given that there are already personalized messages.

But maybe I can take a look at it and make a pull request if I have achieved something.

**Comment by Minecrell** [comment]
> Or, another option that I thought of is to maybe have a completely different description for older clients? I don't think that should be hard to implement given that there are already personalized messages.

Yes, I thought about it too. If I had ever finished SLP 4.0 you would already be able to do this using "triggers" (see my explanation at https://github.com/Minecrell/ServerListPlus/issues/338#issuecomment-828655095). Unfortunately, in SLP 3.0 the available profiles are hardcoded and adding new ones is not very trivial (and kind of messy). :(

**Comment by Minecrell** [comment]
@Epharal1 If you would like to contribute a way to have a completely separate MOTD etc for outdated clients I think it would be best to keep it generic (independent of RGB) and just call it `Outdated` (next to `Default`, `Personalized` and `Banned`). It would trigger whenever some outdated client pings the server, no matter if it supports RGB or not. You can see how `Banned` was added in https://github.com/Minecrell/ServerListPlus/pull/99, the changes you'd need to do for that would be similar.

With the `Outdated` profile, you could either decide to keep it without RGB for all clients, or combine it with what I mentioned above (stripping all RGB colors for clients that don't support it). I think I will add it anyway since it's relatively simple (although it requires messing a bit with replacers and regular expressions).
