### ISSUE TITLE
Potential round-tripping issue with TimeUnitValue class

### ISSUE THREAD

**Issue by mangstadt** [Minecrell/ServerListPlus#356]
This may be a moot issue, but Java 8 added new values to the `TimeUnit` enum. If any of these values are passed into the `TimeUnitValue` constructor, it will treat it as milliseconds when serialized because the serialization logic does not account for the new `TimeUnit` values.

```java
TimeUnitValue v1 = new TimeUnitValue(TimeUnit.MICROSECONDS, 10);
String s = v.serialize().toString(); //returns an integer without a suffix because MICROSECONDS is not part of the UNIT_LOOKUP map
TimeUnitValue v2 = new TimeUnitValue(s); //because the string lacks a suffix, it treats the value as milliseconds
assertEquals(TimeUnit.MICROSECONDS, v2.getUnit()); //fails
```

**Comment by Minecrell** [comment]
Good catch, but as far as I can tell, `TimeUnit.MICROSECONDS` etc exists even in Java 7: https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/TimeUnit.html

I guess I didn't consider those units to be useful for the configuration, that's why I omitted them. There is no way to get an arbitrary `TimeUnit` value into the configuration so it shouldn't ever cause any trouble. Adding them would require making the parsing more complex because you'd probably want two chars like `ms`, `ns` or `us` for them. Not sure if that's worth it given that such short times would be pointless for the purposes in the configuration.

Note that in general it's stupid that some parts of SLP still compile against Java 7. I strongly hope no one uses that anymore. I've only kept that because I didn't want to feel compelled to rewrite all of SLP to make proper use of Java 8 features. (That quickly goes into the large refactoring/rewrite category...)

**Comment by mangstadt** [comment]
> Good catch, but as far as I can tell, TimeUnit.MICROSECONDS etc exists even in Java 7

Thanks! 😀  My mistake, I thought IntelliJ was telling me that they were added in Java 8.

> Note that in general it's stupid that some parts of SLP still compile against Java 7. I strongly hope no one uses that anymore.

Me neither! According to the [Minecraft Wiki](https://minecraft.fandom.com/wiki/Tutorials/Update_Java), Minecraft comes bundled with Java 8, and the latest version of Minecraft (still in development) uses Java 16.

**Comment by Minecrell** [comment]
> According to the Minecraft Wiki, Minecraft comes bundled with Java 8, and the latest version of Minecraft (still in development) uses Java 16.

Technically SLP still supports MC 1.8.3+ which was Java 6+ if I remember correctly. But yeah, we're at Java 16 at this point and really no one should be using Java 7 anymore.

**Comment by Minecrell** [comment]
Closing this for the reason mentioned above (not convinced if it's worth making the parsing more complex to parse values that don't actually make sense).
