### ISSUE TITLE
Error in --Plugin line after change first motd msg.

### ISSUE THREAD

**Issue by KMoDwOne** [Minecrell/ServerListPlus#410]
Hi, i hope my Title represents my Issue. Im not sure its an issue with the hosting service fileeditor or with the Plugins .yml itself.

This is what happens:
When opening the .yml and change something in the File. For example the Server Name, only the default Name(Minecraft) is replaced with the new one.
Then if i want to save the File i get an Error Message wich says there is an Error in the File, i want to ignore it and still save the file. After checking the File again it shows an Error in the --Plugins Line, altough i didnt change anything there.

I also tryed to add only one single Letter, but still the same result. 
This is my first day on Github and also my very first Server, so my knowledge is a little small atm. :D 

Would be super Nice if someone knows what can be the issue here.

Edit:
Ive downloaded the file and edited the same with Notepad++. So i guess its something caused by the Apex Hosting Editor or because i want to change the file inside the Server enviorment. 
Is it possible that there is an issue with other Plugins wich make exactly the Plugins Line show the Error?

**Comment by stephan-gh** [comment]
The `--- !Plugin` lines used by SLP are a bit "special" so it is not entirely surprising that some online editors might be confused by it. It seems unlikely that the error you mentioned is caused by an issue with other plugins. In retrospect making the SLP configuration so "special" was not an ideal design choice from myself (although it had some positive sides as well).

I recommend that you edit the configuration with Notepad++ instead as you tried and avoid touching it in the web UI. Sorry for the inconvenience :)

**Comment by stephan-gh** [comment]
Or if I understand you correctly you could also just ignore the error in the online editor. It sounds like it is wrongly reported (you might want to report this to your server host since the error is likely on their side).

**Comment by KMoDwOne** [comment]
I tryed it out  ignoring the Warning. I saved the file and restarted the server. But there was no change. The part i changed wasnt updated. There was only the 3 default messages.

For sure, i alrdy started a ticket :D

**Comment by stephan-gh** [comment]
You will need to run the `/slp enable` command once. If you don't do that, it will not apply any of your changes.
