### ISSUE TITLE
Sponge Favicon Issue

### ISSUE THREAD

**Issue by JoeSchmo2840** [Minecrell/ServerListPlus#57]
I keep getting "Unknown configuration property: URLs/Files/Folders @ FaviconConf", since its a sponge plugin it resides in the mods folder, and its config in the Config folder. Not sure where to target the files

**Comment by Minecrell** [comment]
Can you paste your configuration?

**Comment by JoeSchmo2840** [comment]
http://pastebin.com/mi6PJD3L

**Comment by Minecrell** [comment]
Basically the configuration consists of 2 main parts: the status config (starting with `!Status`) and the plugin config (starting with `!Plugin`) You always need to add to the status config, not to the plugin config. So instead of putting in Files/Folders/URLs in the plugin section you need to add it to your default or personalized status section.

See this for an example: https://github.com/Minecrell/ServerListPlus/wiki/Examples (with heads instead of files). You need to place the files as specified in your config relative to your serverlistplus config folder then

**Comment by JoeSchmo2840** [comment]
That worked, thanks so much. Ill be more careful in the future and read a little more closely.
