### ISSUE TITLE
"last online" placeholder

### ISSUE THREAD

**Issue by jonthesquirrel** [Minecrell/ServerListPlus#81]
Placeholders would be very useful that would show the relative amount of time since the player was last on the server (eg. 2 days), and another placeholder for that absolute date (eg. Mar 1 2016). There would hopefully also be a way to configure the format of the date/ how specific the time is (eg. 2 days, 5 hours, 30 minutes).

**Comment by Minecrell** [comment]
If I remember correctly I already store this, so should be possible to add.

**Comment by Minecrell** [comment]
I added some in the latest development build. Might not be exactly what you imagined but maybe it is useful to you:

- `%last_online_duration%` - The duration since the player was last online, will automatically choose precision (e.g. `moments ago`, or `2 days ago`)
- `%last_online_precise_duration%` - The precise duraion since the player was last online (e.g. `5 months, 3 days, 5 hours ago`)
- The message itself is not configurable, however there are several translations present which can be choosen like e.g. `%last_online_duration@de`

Otherwise, you can use a date directly:
- `%last_online_date%` - The date when the player was last online (uses the system default date format)
- `%last_online_datetime%` - As above, but includes the time.
- Likewise, you can also choose a locale here: `%last_online_date@de%` (Last online in German date format)

You can also configure the format the date is printed in:
- `%last_online_date|short%` (one of `short`, `medium`, `long`, or `full`, defines how much of the date is included, like if the month names are also included for example)
- `%last_online_date|dd/mm/yy%` (Custom date format string, see https://www.w3.org/TR/NOTE-datetime (-> Formats)

**Comment by Minecrell** [comment]
I'm reopening this for now because it will likely not be in the first version of SLP 4.0.

**Comment by Minecrell** [comment]
This is already in 3.4.5 and now also properly documented.
