### ISSUE TITLE
APIs no longer get correct MOTD Info

### ISSUE THREAD

**Issue by HeroCC** [Minecrell/ServerListPlus#94]
Hello!

I am not sure at what release, but sometime ago banner images & other APIs could no longer get the correct MOTD when running SLP. I expect it to show up as it does on the Spigot page for the plugin:
![image](https://cloud.githubusercontent.com/assets/2124489/14646911/6fb66486-0629-11e6-8bde-c6ff9b04b7eb.png)
but it actually shows like this:
![image](https://cloud.githubusercontent.com/assets/2124489/14646956/8eba0176-0629-11e6-8fd6-7673552acd77.png). Minecraft shows fine and looks as expected.

Some affected services are the [Minecraft Server Status Banner Generator](http://status.mclive.eu/) and [MCApi](https://mcapi.us/), [MCApi.ca](https://mcapi.ca/query/mc.heroicraft.net/info)

**Comment by Minecrell** [comment]
If the Minecraft client shows properly then that is certainly a bug in the status banner generator, not in ServerListPlus. Keep in mind the image on the Spigot page is an ingame screenshot.

I think there were a few internal changes with how the MOTDs are handled on BungeeCord with 1.9+, so that might be the reason why it is failing now and not before.

**Comment by HeroCC** [comment]
But would it affect both services? They both work fine on other Bungee 1.9 servers without SLP from what I can tell (I just tested a few random big servers that I know use bungee). I can set up a test instance and as well and see if there is a difference

**Comment by Minecrell** [comment]
Most custom implementations usually expect the response to use color codes directly (the old format), because the servers used to only respond with that. However the new JSON format which is used by BungeeCord as of 1.9 is actually the new (and better) way, but some of these unofficial sites aren't using it yet.

I haven't changed anything in ServerListPlus, so I highly doubt this caused by something in the plugin. If you can confirm it works on the Minecraft client you will need to tell the developers of the status banner to properly implement the Minecraft protocol specification.

**Comment by Minecrell** [comment]
Not a ServerListPlus issue, you'll need to ask the authors of the unofficial tools to support the specification properly. I'm sorry, but there isn't anything I can do.

Also see https://www.spigotmc.org/threads/open-source-dynamic-minecraft-banner.7123/page-6#post-1482162
